-- =====================================================================
-- Supabase PostgreSQL Schema for eNASR MTR Application
-- Project URL: https://ahmpkflqibikzhfiecgo.supabase.co
-- Paste this script into your Supabase SQL Editor (https://supabase.com/dashboard)
-- =====================================================================

-- 1. Create mtr_routes master header table
CREATE TABLE IF NOT EXISTS public.mtr_routes (
    route_id TEXT PRIMARY KEY,
    route_type TEXT NOT NULL,
    route_name TEXT NOT NULL,
    originating_agency TEXT NOT NULL,
    artcc_facility TEXT NOT NULL,
    floor_alt_ft INTEGER NOT NULL,
    ceiling_alt_ft INTEGER NOT NULL,
    route_width_nm REAL DEFAULT 10.0,
    status TEXT DEFAULT 'ACTIVE',
    geometry_wkt TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create mtr_segments waypoint and corridor sequence table
CREATE TABLE IF NOT EXISTS public.mtr_segments (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id TEXT NOT NULL REFERENCES public.mtr_routes(route_id) ON DELETE CASCADE,
    sequence_num INTEGER NOT NULL,
    point_name TEXT NOT NULL,
    point_type TEXT NOT NULL,
    latitude_dec REAL NOT NULL,
    longitude_dec REAL NOT NULL,
    min_alt_ft INTEGER,
    max_alt_ft INTEGER,
    width_left_nm REAL DEFAULT 5.0,
    width_right_nm REAL DEFAULT 5.0,
    next_point_name TEXT,
    segment_distance_nm REAL,
    geometry_wkt TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_route_sequence UNIQUE(route_id, sequence_num)
);

-- 3. Enable Row Level Security (RLS) policies for API access
ALTER TABLE public.mtr_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mtr_segments ENABLE ROW LEVEL SECURITY;

-- Allow public read access (SELECT)
CREATE POLICY "Allow public read mtr_routes" ON public.mtr_routes FOR SELECT USING (true);
CREATE POLICY "Allow public read mtr_segments" ON public.mtr_segments FOR SELECT USING (true);

-- Writes must go through a trusted backend. Remove the legacy anonymous-write
-- policies as well, so rerunning this migration repairs existing deployments.
DROP POLICY IF EXISTS "Allow public write mtr_routes" ON public.mtr_routes;
DROP POLICY IF EXISTS "Allow public write mtr_segments" ON public.mtr_segments;
